sudo: false
language: go
git:
  depth: 1
install: go get -v github.com/gohugoio/hugo
script:
  - hugo
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: public
  repo: lxzxl/lxzxl.github.io
  fqdn: www.bulma.xyz
  target_branch: master
  email: lxz318@aliyun.com
  name: lxzxl
notifications:
  email:
    on_success: never
